export const gApplicationSchema = {
  gSchemaVersion: 1,
  gSchemaName: "gApplicationSchema",
  title: "Application",
  description:
    "Everything a gPronto.Application repository must hold: its root entries, its link to the framework, its source and public shape, its HTML entry, its configuration, its environment values, and its package.",
  implementation: {
    schemaLocation:
      "GProntoFrameworkApplicationRootComponent.gSchemas.gApplicationSchema",
    runtimeLocation: null,
    consumers: [
      "the application repository conformance checker",
      "the application scaffolder",
    ],
    mode: "validate and generate; never mutate a repository at browser runtime",
    adoption: {
      conformanceCheckRequired: true,
      invalidSchemaBlocksGenerationAndValidation: true,
      currentAssetsRemainAuthoritativeUntilAtomicAdoption: true,
      schemaWinsAfterAdoption: true,
      canonicalAssetsAreGeneratedFromTheSchemaAfterAdoption: true,
      unsupportedVersion: "fail before inspecting or generating an application",
    },
  },
  identity: "a Vite React application in its own Git repository",
  root: {
    trackedFiles: [
      ".gitignore",
      "index.html",
      "package-lock.json",
      "package.json",
      "tsconfig.json",
      "vite.config.ts",
    ],
    otherEntriesAllowed: true,
    gitignore: ["dist/", "gPronto/", "node_modules/", ".local", ".env.local", ".env"],
  },
  frameworkLink: {
    name: "gPronto",
    resolvesTo: "the gPronto.Framework source folder inside a local clone",
    resolvesToAFolder: true,
    committed: false,
    mechanismIsSuppliedByTheOperatingSystem: true,
  },
  source: {
    folder: "src",
    foldersInSource: ["webpages"],
    filesInSource: ["gPronto.Application.Bootstrap.EntryPoint.ts"],
    otherDirectChildrenAllowed: false,
  },
  publicAssets: {
    folder: "public",
    files: ["favicon.svg"],
    foldersAllowed: false,
  },
  htmlEntry: {
    file: "index.html",
    language: "en",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1.0",
    iconHref: "/favicon.svg",
    title: "the Application Name",
    mountElementId: "root",
    scriptType: "module",
    scriptSource: "/src/gPronto.Application.Bootstrap.EntryPoint.ts",
  },
  frameworkResolution: {
    moduleSpecifier: "@gpronto.framework",
    target: "./gPronto/gPronto.Framework.PublicApi.EntryPoint.ts",
    declaredIn: ["vite.config.ts", "tsconfig.json"],
    bothDeclarationsMustAgree: true,
    preserveSymlinks: true,
    environmentPrefixes: ["VITE_", "GPRONTO_"],
    typeScriptInclude: ["src", "gPronto", "vite.config.ts"],
    applicationSourceMayImportTheFrameworkOnlyThroughTheSpecifier: true,
  },
  environment: {
    file: ".env",
    committed: false,
    variables: [
      "GPRONTO_STYLING",
      "VITE_SUPABASE_URL",
      "VITE_SUPABASE_PUBLISHABLE_KEY",
    ],
    exampleFile: false,
    forbiddenValues: [
      "secret key",
      "service-role key",
      "database password",
      "SMTP password",
      "Management API token",
    ],
  },
  package: {
    name: "gpronto-application",
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      preview: "vite preview",
      check: "tsc --noEmit",
      build: "tsc --noEmit && vite build",
    },
    dependencies: {
      "@emotion/react": "11.14.0",
      "@emotion/styled": "11.14.1",
      "@mui/lab": "6.0.1-beta.36",
      "@mui/icons-material": "6.5.0",
      "@mui/material": "6.5.0",
      "@mui/system": "6.5.0",
      "@mui/x-data-grid": "8.29.1",
      "@refinedev/core": "5.0.12",
      "@refinedev/mui": "8.0.2",
      "@refinedev/react-hook-form": "5.0.4",
      "@refinedev/react-router": "2.0.4",
      "@refinedev/supabase": "6.0.2",
      "@supabase/supabase-js": "2.112.1",
      react: "19.2.8",
      "react-dom": "19.2.8",
      "react-hook-form": "7.85.0",
      "react-router": "7.18.2",
    },
    devDependencies: {
      "@types/node": "22.20.1",
      "@types/react": "19.2.18",
      "@types/react-dom": "19.2.4",
      "@vitejs/plugin-react": "6.0.5",
      "json-schema-to-ts": "3.1.1",
      typescript: "5.9.3",
      vite: "8.2.0",
    },
    everyVersionIsPinned: true,
    lockfileIsIdenticalAcrossApplications: true,
  },
  differencesBetweenApplications: [
    "the HTML title",
    "the development port",
    "the preview port",
    "the environment values",
  ],
  everythingElseIsIdenticalAcrossApplications: true,
  conformance: {
    applications: [
      "gPronto.Application.Backstage",
      "gPronto.Application.gPrototype2",
      "gPronto.Application.gPrototype3",
      "gPronto.Application.gPrototype4",
    ],
    validationReadsTheRepositoryWithoutChangingIt: true,
    generationRequiresAnApplicationNameDevelopmentPortPreviewPortAndEnvironmentValues: true,
    generatedFilesMustPassTheSameValidationAsExistingFiles: true,
    frameworkLinkIsValidatedButCreatedByTheOperatingSystem: true,
  },
} as const;
