export const gBootstrapSchema = {
  gSchemaVersion: 1,
  gSchemaName: "gBootstrapSchema",
  title: "Bootstrap",
  description:
    "The bootstrap request that comes in, the application definition that is built from it, the ordered startup steps between them, and what happens when one fails.",
  implementation: {
    schemaLocation:
      "GProntoFrameworkApplicationRootComponent.gSchemas.gBootstrapSchema",
    runtimeLocation: null,
    consumers: ["bootstrapGProntoFrameworkApplication"],
    adoption: {
      conformanceCheckRequired: true,
      invalidSchemaBlocksBootstrap: true,
      currentRuntimeRemainsAuthoritativeUntilAtomicAdoption: true,
      schemaWinsAfterAdoption: true,
      duplicatedRuntimeDefinitionsAreRemovedAfterAdoption: true,
      unsupportedVersion: "fail before any bootstrap side effect",
    },
  },
  entryPoint: "bootstrapGProntoFrameworkApplication",
  successfulCallsPerDocument: 1,
  retryAfterAFailedCall: true,
  calledFrom: "src/gPronto.Application.Bootstrap.EntryPoint.ts",
  schemaCatalog: {
    publicLocation: "GProntoFrameworkApplicationRootComponent.gSchemas",
    exactOwnKeys: [
      "gApplicationSchema",
      "gAuthenticationSchema",
      "gBootstrapSchema",
      "gComponentSchema",
      "gDataResourceSchema",
      "gFormatSchema",
      "gIconSchema",
      "gLayoutSchema",
      "gNotificationSchema",
      "gOrganisationSchema",
      "gPostgresDataContractSchema",
      "gSessionSchema",
      "gStorageSchema",
      "gStylingSchema",
      "gSupabaseSchema",
      "gTelemetrySchema",
      "gUserSchema",
      "gValidationSchema",
      "gValueCodecSchema",
      "gWebpageSchema",
    ],
    entry: {
      datatype: "plain deeply immutable data object",
      required: true,
      nullable: false,
      firstOwnKey: "gSchemaVersion",
      gSchemaVersion: 1,
      gSchemaNameMustEqualTheCatalogKey: true,
      functionsAllowed: false,
      symbolsAllowed: false,
      jsonSerializationMustSucceed: true,
    },
    registryCreatedBeforeAnySchemaConsumerStarts: true,
    registryFactoryRecursivelyFreezesEverySchemaBeforeExposure: true,
    publicFacadePropertyIsEnumerableReadonlyAndNonConfigurable: true,
    registryPatternIsImplementationInfrastructureNotADomainGSchema: true,
    facadePatternIsImplementationInfrastructureNotADomainGSchema: true,
    versioning: {
      versionKeyRemainsTheFirstOwnKey: true,
      interpretationChangeIncrementsTheIntegerInTheSameSchemaFile: true,
      parallelVersionedSchemaFilesAreNotCreated: true,
      eachConsumerDeclaresItsSupportedVersions: true,
      unsupportedVersionFailsBeforeTheConsumerPerformsASideEffect: true,
    },
  },
  request: {
    styling: {
      datatype: "stylingIdentifier",
      required: true,
      nullable: false,
      source: "import.meta.env.GPRONTO_STYLING",
    },
    supabase: {
      datatype: "supabaseConfiguration",
      required: true,
      nullable: false,
    },
    webpageModules: {
      datatype: "Readonly<Record<string, unknown>>",
      required: true,
      nullable: false,
      source: "an eager import of every src/webpages/**/webpage.tsx",
    },
  },
  requestKeys: ["styling", "supabase", "webpageModules"],
  definition: {
    styling: {
      datatype: "stylingIdentifier",
      required: true,
      nullable: false,
    },
    webpages: {
      datatype: "registeredWebpageDefinitionRegistry",
      required: true,
      nullable: false,
    },
    supabase: {
      datatype: "supabaseConfiguration",
      required: true,
      nullable: false,
    },
  },
  definitionKeys: ["styling", "webpages", "supabase"],
  steps: [
    "start the notification runtime for the document",
    "refuse a second bootstrap of the same document",
    "read the element with the id root",
    "resolve the styling option from its identifier",
    "apply the resolved styling to the notification runtime",
    "validate the Supabase configuration",
    "build the registered-webpage registry from the supplied modules",
    "build the application definition",
    "create the React root on the root element",
    "render the application root inside the notification error boundary and React Strict Mode",
    "record the document as bootstrapped",
  ],
  webpageModuleDiscovery: {
    eager: true,
    sortedByModulePathBeforeRegistration: true,
    everyModuleMustExport: "webpage",
    error:
      "The discovered webpage module \"<modulePath>\" must export \"webpage\".",
  },
  failure: {
    unmountsTheRootWhenOneWasCreated: true,
    reportsTheError: true,
    rethrows: true,
    notificationRuntimeSurvives: true,
  },
  errors: {
    secondBootstrap:
      "The gPronto.Framework application has already been bootstrapped for this document.",
    missingRootElement: "The application root element is missing.",
  },
  ownedByTheApplication: ["styling", "supabase", "webpageModules"],
  ownedByTheFramework: [
    "the React root",
    "the webpage registry",
    "the application definition",
    "the render",
  ],
} as const;
