export const gIconSchema = {
  gSchemaVersion: 1,
  gSchemaName: "gIconSchema",
  title: "Icon",
  description:
    "Every icon name, and the icon each variant uses when none is supplied.",
  implementation: {
    schemaLocation:
      "GProntoFrameworkApplicationRootComponent.gSchemas.gIconSchema",
    runtimeLocation: "GProntoFrameworkApplicationRootComponent.Styles.Icons",
    consumers: [
      "the icon registry factory",
      "gComponents that resolve icons by name",
    ],
    adoption: {
      conformanceCheckRequired: true,
      invalidSchemaBlocksIconRegistryCreation: true,
      currentRegistryRemainsAuthoritativeUntilAtomicAdoption: true,
      schemaWinsAfterAdoption: true,
      duplicatedIconNamesAndVariantDefaultsAreRemovedAfterAdoption: true,
      unsupportedVersion: "fail before the icon registry is exposed",
    },
  },
  catalogLocation: "GProntoFrameworkApplicationRootComponent.Styles.Icons",
  namePattern: "^([A-Z][a-z0-9]+)+$",
  registeredIconCount: 51,
  registryEntry: {
    key: {
      datatype: "string",
      required: true,
      nullable: false,
      pattern: "^([A-Z][a-z0-9]+)+$",
    },
    value: {
      datatype: "MuiSvgIcon component",
      required: true,
      nullable: false,
    },
  },
  immutable: true,
  variantDefaults: {
    button: {
      primary: "Save",
      secondary: "MoreActions",
      danger: "Delete",
      omittedIconUsesTheVariantDefault: true,
      nullIconRendersNoIcon: true,
    },
  },
  families: {
    resource: [
      "SingleColumnLayoutShowcase",
      "Users",
      "Organisations",
      "Settings",
      "Logs",
      "UserEvents",
      "UserSessions",
      "EmailTemplates",
      "AuditEvents",
      "DataExamples",
      "Projects",
      "ProjectTasks",
      "ProjectPrototypes",
      "ProjectUserAccessGrants",
      "GatekeeperSessions",
      "ProjectPrototypeUsers",
      "ProjectPrototypeOrganisations",
      "ProjectPrototypeSettings",
      "ProjectPrototypeLogs",
      "ProjectPrototypeUserEvents",
      "ProjectPrototypeUserSessions",
      "ProjectPrototypeEmailTemplates",
      "ProjectPrototypeAuditEvents",
    ],
    authentication: [
      "AuthenticationSignIn",
      "AuthenticationSignOut",
      "AuthenticationSignUp",
      "AuthenticationInvitationAccept",
      "AuthenticationMagicLinkRequest",
      "AuthenticationPasswordRecovery",
      "AuthenticationPasswordReset",
      "AuthenticationPasswordChange",
      "AuthenticationEmailChange",
      "AuthenticationConfirmationResend",
      "AuthenticationReauthenticate",
      "AuthenticationCallback",
      "AuthenticationLoading",
      "AuthenticationError",
      "AuthenticationSuccess",
    ],
    action: [
      "Create",
      "Edit",
      "Delete",
      "Save",
      "Search",
      "Filter",
      "Refresh",
      "ViewDetails",
      "MoreActions",
      "Copy",
      "Download",
      "Upload",
      "Close",
    ],
  },
} as const;
