export const gOrganisationSchema = {
  gSchemaVersion: 1,
  gSchemaName: "gOrganisationSchema",
  title: "Organisation",
  description:
    "The complete public Organisation object: field names, datatypes, defaults, hydration sources, write access, persistence, publication, and trust boundary.",
  implementation: {
    schemaLocation:
      "GProntoFrameworkApplicationRootComponent.gSchemas.gOrganisationSchema",
    runtimeLocation: "GProntoFrameworkApplicationRootComponent.Organisation",
    consumers: [
      "the public-properties default factory",
      "the public Organisation interface factory",
      "the public-properties storage codec",
      "the authentication hydration mapper",
    ],
    adoption: {
      conformanceCheckRequired: true,
      invalidSchemaBlocksConsumerStartup: true,
      currentRuntimeRemainsAuthoritativeUntilAdopted: true,
      adoptionIsAtomicPerSchema: true,
      schemaWinsAfterAdoption: true,
      duplicatedRuntimeDefinitionsAreRemovedAfterAdoption: true,
      unsupportedVersion:
        "throw before an Organisation value is created or hydrated",
    },
  },
  object: {
    alwaysPresent: true,
    nullable: false,
    extensible: false,
    facadePropertyDescriptor: {
      writable: false,
      configurable: false,
      enumerable: true,
    },
  },
  fieldOrder: [
    "OrganisationId",
    "Name",
    "Type",
    "ProfileUrl",
    "Kyb",
    "Settings",
  ],
  fields: {
    OrganisationId: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.organisation.id",
    },
    Name: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.organisation.name",
    },
    Type: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.organisation.organisation_type",
    },
    ProfileUrl: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    Kyb: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    Settings: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
  },
  hydration: {
    requires:
      "an active visible organisation row linked from the hydrated user row",
    absentOrganisationUsesEveryFieldDefault: true,
    organisationIdMustEqualHydratedUserOrganisationId: true,
  },
  assignment: {
    nonStringValueThrows: "TypeError",
    equalValueDoesNothing: true,
    changedValueWritesCompletePublicPropertiesEnvelopeFirst: true,
    changedValuePublishesOneImmutableSnapshot: true,
    changedValueUpdatesReactSubscribers: true,
    changedValueIsVisibleToOtherTabs: true,
    readsOrWritesADatabaseRow: false,
    preservesSessionValues: true,
    concurrentWrites: "the last completed localStorage write wins",
  },
  replacement: {
    performedBy: "the authentication runtime",
    validatesEveryFieldAsAString: true,
    writesBeforePublishing: true,
    publishesOneSnapshot: true,
  },
  trust: {
    source: "browser-controlled cached state",
    authoritativeForAuthorization: false,
    provesASession: false,
    usableByRlsPolicies: false,
  },
} as const;
