export const gPostgresDataContractSchema = {
  gSchemaVersion: 1,
  gSchemaName: "gPostgresDataContractSchema",
  title: "gPostgresDataContract",
  description: "Everything a gPostgresDataContract file must hold.",
  implementation: {
    schemaLocation:
      "GProntoFrameworkApplicationRootComponent.gSchemas.gPostgresDataContractSchema",
    runtimeLocation:
      "GProntoFrameworkApplicationRootComponent.gPostgresDataContracts",
    consumers: [
      "the gPostgresDataContract conformance checker",
      "the gPostgresDataContract registry factory",
      "the PostgreSQL data-resource definition factory",
      "schema-driven PostgreSQL gComponents",
    ],
    adoption: {
      conformanceCheckRequired: true,
      invalidContractBlocksRegistryCreation: true,
      currentContractsRemainAuthoritativeUntilAtomicAdoption: true,
      schemaWinsAfterAdoption: true,
      duplicatedContractValidationRulesAreRemovedAfterAdoption: true,
      unsupportedVersion: "fail before any data contract is registered",
    },
  },
  folder: {
    parent: "gPronto.Framework/gPostgresDataContracts",
    fileNamePattern:
      "^gPostgresDataContract\\.([A-Z][a-z0-9]+)+_v[1-9][0-9]*\\.ts$",
    nameEndsWith: "s",
    versionsPerFile: 1,
  },
  exports: {
    count: 2,
    identifier: {
      name: "Postgres<Name>_v<N>",
      value: "postgres_<snake_name>_v<N>",
    },
    schema: { name: "<Singular>PostgresDataContractSchema_v<N>" },
    importsAllowed: false,
    defaultExportAllowed: false,
    publicExportBarrel:
      "gPronto.Framework.PublicApi.PostgresDataResourceExports.ts",
    schemaExportedPublicly: false,
  },
  describes: {
    source: "exactly one PostgreSQL table",
    viewsAllowed: false,
  },
  contractShape: {
    exactOwnKeys: [
      "gPostgresDataContract_Schema_Version",
      "title",
      "description",
      "columns",
    ],
    fields: {
      gPostgresDataContract_Schema_Version: {
        datatype: "number",
        required: true,
        nullable: false,
        value: 1,
      },
      title: { datatype: "string", required: true, nullable: false },
      description: { datatype: "string", required: true, nullable: true },
      columns: {
        datatype: "Record<string, columnDefinition>",
        required: true,
        nullable: false,
        minimumOwnKeys: 1,
      },
    },
  },
  columnShape: {
    exactOwnKeysByDatatype: {
      scalar: [
        "description",
        "postgres_datatype",
        "validation",
        "insert",
        "update",
        "datatable",
        "references",
        "isIdColumn",
      ],
      array: [
        "description",
        "postgres_datatype",
        "validation",
        "items",
        "insert",
        "update",
        "datatable",
        "references",
        "isIdColumn",
      ],
    },
    fields: {
      description: { datatype: "string", required: true, nullable: true },
      postgres_datatype: {
        datatype: "postgresDatatype",
        required: true,
        nullable: false,
      },
      validation: {
        datatype: "validationDefinition",
        required: true,
        nullable: false,
      },
      items: {
        datatype: "arrayItemDefinition",
        required: false,
        nullable: false,
        requiredWhen: "postgres_datatype is text[]",
        forbiddenWhen: "postgres_datatype is not text[]",
      },
      insert: {
        datatype: "writeContextDefinition",
        required: true,
        nullable: false,
      },
      update: {
        datatype: "writeContextDefinition",
        required: true,
        nullable: false,
      },
      datatable: {
        datatype: "datatableDefinition",
        required: true,
        nullable: false,
      },
      references: {
        datatype: "referenceDefinition",
        required: true,
        nullable: true,
      },
      isIdColumn: {
        datatype: "boolean",
        required: true,
        nullable: false,
      },
    },
  },
  validationShape: {
    requiredOwnKeys: [
      "allow_null",
      "validate_enum",
      "validate_regex",
      "validate_string_min_length",
      "validate_string_max_length",
      "validate_number_min",
      "validate_number_max",
      "validate_number_precision",
      "validate_number_scale",
    ],
    optionalOwnKeys: ["validators"],
    unknownOwnKeysAllowed: false,
    fields: {
      allow_null: { datatype: "boolean", required: true, nullable: false },
      validate_enum: {
        datatype: "readonly (string | number | boolean)[]",
        required: true,
        nullable: true,
      },
      validate_regex: { datatype: "string", required: true, nullable: true },
      validate_string_min_length: {
        datatype: "non-negative integer",
        required: true,
        nullable: true,
      },
      validate_string_max_length: {
        datatype: "non-negative integer",
        required: true,
        nullable: true,
      },
      validate_number_min: {
        datatype: "number",
        required: true,
        nullable: true,
      },
      validate_number_max: {
        datatype: "number",
        required: true,
        nullable: true,
      },
      validate_number_precision: {
        datatype: "positive integer",
        required: true,
        nullable: true,
      },
      validate_number_scale: {
        datatype: "non-negative integer",
        required: true,
        nullable: true,
      },
      validators: {
        datatype: "readonly validationDescriptor[]",
        required: false,
        nullable: false,
      },
    },
  },
  arrayItemShape: {
    exactOwnKeys: ["validation"],
    fields: {
      validation: {
        datatype: "validationDefinition",
        required: true,
        nullable: false,
      },
    },
  },
  writeContextShape: {
    exactOwnKeys: [
      "label",
      "short_description",
      "format",
      "allowed",
      "required",
      "default",
      "default_expression",
      "gcomponent",
    ],
    fields: {
      label: { datatype: "string", required: true, nullable: false },
      short_description: {
        datatype: "string",
        required: true,
        nullable: true,
      },
      format: { datatype: "formatKey", required: true, nullable: false },
      allowed: { datatype: "boolean", required: true, nullable: false },
      required: { datatype: "boolean", required: true, nullable: false },
      default: { datatype: "unknown", required: true, nullable: true },
      default_expression: {
        datatype: "string",
        required: true,
        nullable: true,
      },
      gcomponent: {
        datatype: "configuredInputSelector",
        required: true,
        nullable: true,
      },
    },
  },
  datatableShape: {
    exactOwnKeys: [
      "label",
      "short_description",
      "format",
      "can_be_visible_in_table",
      "default_visible_in_table",
      "sortable",
      "filterable",
      "default_sort",
    ],
    fields: {
      label: { datatype: "string", required: true, nullable: false },
      short_description: {
        datatype: "string",
        required: true,
        nullable: true,
      },
      format: { datatype: "formatKey", required: true, nullable: false },
      can_be_visible_in_table: {
        datatype: "boolean",
        required: true,
        nullable: false,
      },
      default_visible_in_table: {
        datatype: "boolean",
        required: true,
        nullable: false,
      },
      sortable: { datatype: "boolean", required: true, nullable: false },
      filterable: { datatype: "boolean", required: true, nullable: false },
      default_sort: {
        datatype: "sortOrder",
        required: true,
        nullable: true,
      },
    },
  },
  referenceShape: {
    status: "reserved for the first schema version that defines references",
    currentAllowedValue: null,
  },
  topLevelKeyOrder: [
    "gPostgresDataContract_Schema_Version",
    "title",
    "description",
    "columns",
  ],
  columnKeyOrder: {
    nonArray: [
      "description",
      "postgres_datatype",
      "validation",
      "insert",
      "update",
      "datatable",
      "references",
      "isIdColumn",
    ],
    array: [
      "description",
      "postgres_datatype",
      "validation",
      "items",
      "insert",
      "update",
      "datatable",
      "references",
      "isIdColumn",
    ],
  },
  validationKeyOrder: [
    "allow_null",
    "validate_enum",
    "validate_regex",
    "validate_string_min_length",
    "validate_string_max_length",
    "validate_number_min",
    "validate_number_max",
    "validate_number_precision",
    "validate_number_scale",
  ],
  validationOptionalKey: "validators",
  itemsKeys: ["validation"],
  writeContextKeyOrder: [
    "label",
    "short_description",
    "format",
    "allowed",
    "required",
    "default",
    "default_expression",
    "gcomponent",
  ],
  datatableKeyOrder: [
    "label",
    "short_description",
    "format",
    "can_be_visible_in_table",
    "default_visible_in_table",
    "sortable",
    "filterable",
    "default_sort",
  ],
  rules: {
    idColumnsPerSchema: 1,
    idColumnDatatype: "uuid",
    idColumnInsertAllowed: false,
    idColumnUpdateAllowed: false,
    idColumnDefaultExpression: "gen_random_uuid()",
    defaultSortColumnsPerSchema: "at most 1",
    updateRequiredAlwaysFalse: true,
    insertRequiredImpliesInsertAllowed: true,
    atMostOneOf: ["default", "default_expression"],
    gcomponentNullWhenNotAllowed: true,
    formatMustBeAKeyOf: "the format catalog node for the column datatype",
    validatorsMustConformTo: "gValidationSchema.descriptor",
    gcomponentMustBeAKeyOf:
      "gPostgresDataContractSchema.valueSets.configuredInputSelector",
    datatableDefaultVisibilityRequiresCanBeVisibleInTable: true,
    datatableDefaultSortRequiresSortable: true,
    releasedVersionsAreImmutable: true,
    firstVersionNumber: 1,
    laterVersionNumber:
      "the highest version number already used for that name, plus one",
  },
  valueSets: {
    postgresDatatype: {
      exactValues: [
        "uuid",
        "text",
        "extensions.citext",
        "integer",
        "boolean",
        "date",
        "timestamp with time zone",
        "jsonb",
        "text[]",
      ],
      numericPattern: "^numeric\\([1-9][0-9]*,[0-9]+\\)$",
      numericScaleMustNotExceedPrecision: true,
    },
    configuredInputSelector: {
      GComponentInputCheckbox: "checkbox",
      GComponentInputDate: "date",
      GComponentInputDateTime: "date-time",
      GComponentInputEmail: "email",
      GComponentInputNumber: "number",
      GComponentInputText: "text",
      GComponentInputTextarea: "textarea",
      GComponentInputUrl: "url",
    },
    sortOrder: ["asc", "desc"],
  },
} as const;
