export const gStylingSchema = {
  gSchemaVersion: 1,
  gSchemaName: "gStylingSchema",
  title: "Styling",
  description:
    "Everything a styling option must hold: its folder, file, and runtime identifier, and the structure of its CSS file.",
  implementation: {
    schemaLocation:
      "GProntoFrameworkApplicationRootComponent.gSchemas.gStylingSchema",
    runtimeLocation: "GProntoFrameworkApplicationRootComponent.gStylings",
    consumers: [
      "the styling registry factory",
      "the styling conformance checker",
      "the bootstrap styling resolver",
    ],
    adoption: {
      conformanceCheckRequired: true,
      invalidSchemaOrStylingBlocksRegistryCreation: true,
      currentRegistryRemainsAuthoritativeUntilAtomicAdoption: true,
      schemaWinsAfterAdoption: true,
      duplicatedStylingIdentifiersAndCssRulesAreRemovedAfterAdoption: true,
      unsupportedVersion: "fail before the styling registry is exposed",
    },
  },
  registryLocation: "GProntoFrameworkApplicationRootComponent.gStylings",
  selectedBy: "the styling value in the bootstrap request",
  folder: {
    parent: "gPronto.Framework/gStylings",
    namePattern: "^gStyling-[a-z0-9]+(?:-[a-z0-9]+)*$",
    fileName: "<folder name>.css",
    fileCount: 1,
    subfoldersAllowed: false,
    filesDirectlyInParentAllowed: false,
  },
  option: {
    exactOwnKeys: ["identifier", "css"],
    fields: {
      identifier: {
        datatype: "string",
        required: true,
        nullable: false,
        equals: "the folder name",
      },
      css: {
        datatype: "string",
        required: true,
        nullable: false,
        source: "the option's CSS file, inlined",
      },
    },
  },
  registered: ["gStyling-1", "gStyling-2"],
  unregisteredIdentifierThrows: true,
  className: {
    derivedFrom: "the complete name of the owning gComponent or gLayout",
    gComponentPrefixForm: "gcomponent-<kebab-case name>",
    gLayoutPrefixForm: "glayout-<kebab-case name>",
    ownersPerClass: 1,
    ownershipTransfersToAParent: false,
    selectorsMayCombineClassesOfDifferentOwners: false,
    everyClassSelectorMustMatchAClassTheSourceCanAssign: true,
  },
  variantModifier: {
    form: "<owner-root-class>--<variant-value>",
    variantValuePattern: "^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$",
    assignedOnEveryRender: true,
    assignedForTheDefaultVariantToo: true,
    modifiersPerRender: 1,
    reusableAcrossOwners: false,
  },
  selector: {
    everyRuleHasExactlyOneSelector: true,
    commaSeparatedSelectorListsAllowed: false,
    duplicateDeclarationsAreWrittenAsSeparateRules: true,
    everySelectorContainsAtLeastOneClass: true,
    exceptTheGlobalResetSequence: true,
    classNamePrefixes: ["gcomponent-", "glayout-"],
    typeSelectorsAllowed: false,
    universalSelectorsAllowed: false,
    idSelectorsAllowed: false,
    attributeSelectorsAllowed: false,
    pseudoSelectorsMustAttachToAnOwnedClass: true,
    unscopedPseudoSelectorsAllowed: [":root", "*::before", "*::after"],
  },
  globalResetSelectorSequence: [
    ":root",
    "html",
    "*",
    "*::before",
    "*::after",
    "body",
  ],
  rootCustomProperties: {
    rootDefinesOnlyCustomProperties: true,
    mayBeOmitted: true,
    allowList: [
      "--gpronto-color-brand-primary",
      "--gpronto-color-brand-primary-hover",
      "--gpronto-color-brand-primary-active",
      "--gpronto-color-state-success",
      "--gpronto-color-state-info",
      "--gpronto-color-state-error",
      "--gpronto-color-state-warning",
      "--gpronto-color-state-hover",
      "--gpronto-color-state-selected",
      "--gpronto-color-surface-standard",
      "--gpronto-color-surface-subtle",
      "--gpronto-color-surface-elevated",
      "--gpronto-color-surface-disabled",
      "--gpronto-color-border-standard",
      "--gpronto-color-border-secondary",
      "--gpronto-color-border-control-hover",
      "--gpronto-color-text-primary",
      "--gpronto-color-text-secondary",
      "--gpronto-color-text-disabled",
      "--gpronto-font-family-standard",
      "--gpronto-font-size-base",
      "--gpronto-line-height-standard",
      "--gpronto-height-control-standard",
      "--gpronto-radius-compact",
      "--gpronto-radius-standard",
    ],
  },
  parityAcrossOptions: {
    sameRuleCount: true,
    sameSelectorAtEachPosition: true,
    sameSelectorOrder: true,
    sameRootPropertyNamesInTheSameOrder: true,
    emptySelectorBlocksAreKeptToPreserveParity: true,
    declarationsInsideCorrespondingBlocksMayDiffer: true,
    customPropertyValuesMayDiffer: true,
  },
} as const;
