export const gUserSchema = {
  gSchemaVersion: 1,
  gSchemaName: "gUserSchema",
  title: "User",
  description:
    "The complete public User object: field names, datatypes, defaults, hydration sources, write access, persistence, publication, and trust boundary.",
  implementation: {
    schemaLocation:
      "GProntoFrameworkApplicationRootComponent.gSchemas.gUserSchema",
    runtimeLocation: "GProntoFrameworkApplicationRootComponent.User",
    consumers: [
      "the public-properties default factory",
      "the public User interface factory",
      "the public-properties storage codec",
      "the authentication hydration mapper",
    ],
    adoption: {
      conformanceCheckRequired: true,
      invalidSchemaBlocksConsumerStartup: true,
      currentRuntimeRemainsAuthoritativeUntilAdopted: true,
      adoptionIsAtomicPerSchema: true,
      schemaWinsAfterAdoption: true,
      duplicatedRuntimeDefinitionsAreRemovedAfterAdoption: true,
      unsupportedVersion: "throw before a User value is created or hydrated",
    },
  },
  object: {
    alwaysPresent: true,
    nullable: false,
    extensible: false,
    facadePropertyDescriptor: {
      writable: false,
      configurable: false,
      enumerable: true,
    },
  },
  fieldOrder: [
    "UserId",
    "AuthUserId",
    "Email",
    "FirstName",
    "LastName",
    "Role",
    "RoleApplication",
    "RolePrototype",
    "OrganisationId",
    "ProfileUrl",
    "Language",
    "Locale",
    "CurrencyCode",
    "DateFormat",
    "DatetimeFormat",
    "CurrencyFormat",
    "Blocked",
    "CanInitiate",
    "CanProcess",
    "Kyc",
    "Settings",
  ],
  fields: {
    UserId: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.user.id",
    },
    AuthUserId: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "the latest Supabase session user id",
    },
    Email: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "the latest Supabase session email",
    },
    FirstName: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.user.first_name",
    },
    LastName: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.user.last_name",
    },
    Role: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.user.role",
      hydrationAllowedValues: ["standard", "admin"],
    },
    RoleApplication: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.user.role_application",
      nullHydrationUsesDefault: true,
    },
    RolePrototype: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.user.role_prototype",
      nullHydrationUsesDefault: true,
    },
    OrganisationId: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: "hydration.user.organisation_id",
      nullHydrationUsesDefault: true,
    },
    ProfileUrl: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    Language: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    Locale: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    CurrencyCode: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    DateFormat: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    DatetimeFormat: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    CurrencyFormat: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    Blocked: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    CanInitiate: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    CanProcess: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    Kyc: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
    Settings: {
      datatype: "string",
      required: true,
      nullable: false,
      default: "-",
      writable: true,
      hydratedFrom: null,
    },
  },
  assignment: {
    nonStringValueThrows: "TypeError",
    equalValueDoesNothing: true,
    changedValueWritesCompletePublicPropertiesEnvelopeFirst: true,
    changedValuePublishesOneImmutableSnapshot: true,
    changedValueUpdatesReactSubscribers: true,
    changedValueIsVisibleToOtherTabs: true,
    readsOrWritesADatabaseRow: false,
    preservesSessionValues: true,
    concurrentWrites: "the last completed localStorage write wins",
  },
  replacement: {
    performedBy: "the authentication runtime",
    validatesEveryFieldAsAString: true,
    writesBeforePublishing: true,
    publishesOneSnapshot: true,
  },
  trust: {
    source: "browser-controlled cached state",
    authoritativeForAuthorization: false,
    provesASession: false,
    usableByRlsPolicies: false,
  },
} as const;
