export const PostgresProjectPrototypeUsers_v1 =
  "postgres_project_prototype_users_v1";

export const ProjectPrototypeUserPostgresDataContractSchema_v1 = {
  gPostgresDataContract_Schema_Version: 1,
  title: "Project Prototype User",
  description: null,
  columns: {
    id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: "gen_random_uuid()",
        gcomponent: null,
      },
      update: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: true,
    },
    created_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: "desc",
      },
      references: null,
      isIdColumn: false,
    },
    updated_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      datatable: {
        label: "Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    is_deleted: {
      description: null,
      postgres_datatype: "boolean",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: false,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      update: {
        label: "Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      datatable: {
        label: "Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    prototype_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Prototype ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Prototype ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Prototype ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    organisation_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Organisation ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Organisation ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Organisation ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_auth_user_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Authentication User ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source Authentication User ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source Authentication User ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_organisation_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Organisation ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source Organisation ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source Organisation ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_first_name: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source First Name",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source First Name",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source First Name",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_last_name: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Last Name",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source Last Name",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source Last Name",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_role: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Role",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source Role",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source Role",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_role_application: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Application Role",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source Application Role",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source Application Role",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_role_prototype: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Prototype Role",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source Prototype Role",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source Prototype Role",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_created_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      update: {
        label: "Source Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      datatable: {
        label: "Source Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_updated_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      update: {
        label: "Source Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      datatable: {
        label: "Source Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_email: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
        validate_string_min_length: 0,
        validate_string_max_length: 320,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Email",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputEmail",
      },
      update: {
        label: "Source Email",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputEmail",
      },
      datatable: {
        label: "Source Email",
        short_description: null,
        format: "extensions.citext.email_link",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source_is_deleted: {
      description: null,
      postgres_datatype: "boolean",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      update: {
        label: "Source Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      datatable: {
        label: "Source Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
  },
};
