export const PostgresGatekeeperSessions_v1 = "postgres_gatekeeper_sessions_v1";

export const GatekeeperSessionPostgresDataContractSchema_v1 = {
  gPostgresDataContract_Schema_Version: 1,
  title: "Gatekeeper Session",
  description: null,
  columns: {
    id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: "gen_random_uuid()",
        gcomponent: null,
      },
      update: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: true,
    },
    created_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Created At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: "desc",
      },
      references: null,
      isIdColumn: false,
    },
    updated_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      datatable: {
        label: "Updated At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    is_deleted: {
      description: null,
      postgres_datatype: "boolean",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: false,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      update: {
        label: "Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      datatable: {
        label: "Is Deleted",
        short_description: null,
        format: "boolean.yes_no",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    auth_user_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Authentication User ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Authentication User ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Authentication User ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    auth_session_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Authentication Session ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Authentication Session ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Authentication Session ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    token_hash: {
      description: null,
      postgres_datatype: "text",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 1,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Token Hash",
        short_description: null,
        format: "text.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Token Hash",
        short_description: null,
        format: "text.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Token Hash",
        short_description: null,
        format: "text.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    expires_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Expires At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      update: {
        label: "Expires At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      datatable: {
        label: "Expires At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    revoked_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Revoked At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      update: {
        label: "Revoked At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputDateTime",
      },
      datatable: {
        label: "Revoked At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    hard_expires_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Hard Expires At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "(now() + '30 days'::interval)",
        gcomponent: null,
      },
      update: {
        label: "Hard Expires At",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Hard Expires At",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
  },
};
