export const PostgresUserEvents_v2 = "postgres_user_events_v2";

export const UserEventPostgresDataContractSchema_v2 = {
  gPostgresDataContract_Schema_Version: 1,
  title: "User event",
  description: null,
  columns: {
    id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: "gen_random_uuid()",
        gcomponent: null,
      },
      update: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: true,
    },
    created_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: "desc",
      },
      references: null,
      isIdColumn: false,
    },
    updated_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      datatable: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    is_deleted: {
      description: null,
      postgres_datatype: "boolean",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: false,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      update: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      datatable: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    is_backstage_mirrored: {
      description: null,
      postgres_datatype: "boolean",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Is backstage mirrored",
        short_description: null,
        format: "boolean.yes_no",
        allowed: false,
        required: false,
        default: false,
        default_expression: null,
        gcomponent: null,
      },
      update: {
        label: "Is backstage mirrored",
        short_description: null,
        format: "boolean.yes_no",
        allowed: false,
        required: false,
        default: false,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Is backstage mirrored",
        short_description: null,
        format: "boolean.yes_no",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    actor_auth_user_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Actor auth user ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: "auth.uid()",
        gcomponent: null,
      },
      update: {
        label: "Actor auth user ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Actor auth user ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    actor_user_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Actor user ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Actor user ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Actor user ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    event_type: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 1,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Event type",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Event type",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Event type",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    source: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 1,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Source",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: "web",
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Source",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Source",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    route: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Route",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Route",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Route",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    page_id: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Page ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Page ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Page ID",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    entity_type: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Entity type",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Entity type",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Entity type",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    entity_id: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Entity ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Entity ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Entity ID",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    request_id: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Request ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Request ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Request ID",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    session_id: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 0,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Session ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Session ID",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Session ID",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    metadata: {
      description: null,
      postgres_datatype: "jsonb",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Metadata",
        short_description: null,
        format: "jsonb.pretty",
        allowed: true,
        required: false,
        default: {},
        default_expression: null,
        gcomponent: "GComponentInputTextarea",
      },
      update: {
        label: "Metadata",
        short_description: null,
        format: "jsonb.pretty",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputTextarea",
      },
      datatable: {
        label: "Metadata",
        short_description: null,
        format: "jsonb.compact",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: false,
        filterable: false,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
  },
};
