export const PostgresSettings_v1 = "postgres_settings_v1";

export const SettingPostgresDataContractSchema_v1 = {
  gPostgresDataContract_Schema_Version: 1,
  title: "Setting",
  description: null,
  columns: {
    id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: "gen_random_uuid()",
        gcomponent: null,
      },
      update: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: true,
    },
    created_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: "desc",
      },
      references: null,
      isIdColumn: false,
    },
    updated_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      datatable: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    is_deleted: {
      description: null,
      postgres_datatype: "boolean",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: false,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      update: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      datatable: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    owner_type: {
      description: null,
      postgres_datatype: "text",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 1,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Owner type",
        short_description: null,
        format: "text.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Owner type",
        short_description: null,
        format: "text.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Owner type",
        short_description: null,
        format: "text.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    owner_id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: true,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Owner ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Owner ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Owner ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    setting_key: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 1,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Setting key",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Setting key",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Setting key",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    setting_value: {
      description: null,
      postgres_datatype: "jsonb",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Setting value",
        short_description: null,
        format: "jsonb.pretty",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputTextarea",
      },
      update: {
        label: "Setting value",
        short_description: null,
        format: "jsonb.pretty",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputTextarea",
      },
      datatable: {
        label: "Setting value",
        short_description: null,
        format: "jsonb.compact",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: false,
        filterable: false,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
  },
};
