export const PostgresOrganisations_v1 = "postgres_organisations_v1";

export const OrganisationPostgresDataContractSchema_v1 = {
  gPostgresDataContract_Schema_Version: 1,
  title: "Organisation",
  description: null,
  columns: {
    id: {
      description: null,
      postgres_datatype: "uuid",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 36,
        validate_string_max_length: 36,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: "gen_random_uuid()",
        gcomponent: null,
      },
      update: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "ID",
        short_description: null,
        format: "uuid.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: true,
    },
    created_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: null,
      },
      datatable: {
        label: "Created at",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: "desc",
      },
      references: null,
      isIdColumn: false,
    },
    updated_at: {
      description: null,
      postgres_datatype: "timestamp with time zone",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      update: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        allowed: false,
        required: false,
        default: null,
        default_expression: "now()",
        gcomponent: null,
      },
      datatable: {
        label: "Updated at",
        short_description: null,
        format: "timestamp with time zone.short",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    is_deleted: {
      description: null,
      postgres_datatype: "boolean",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: null,
        validate_string_max_length: null,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: false,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      update: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputCheckbox",
      },
      datatable: {
        label: "Is deleted",
        short_description: null,
        format: "boolean.yes_no",
        can_be_visible_in_table: true,
        default_visible_in_table: false,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    name: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 1,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Name",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Name",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Name",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
    organisation_type: {
      description: null,
      postgres_datatype: "extensions.citext",
      validation: {
        allow_null: false,
        validate_enum: null,
        validate_regex: null,
        validate_string_min_length: 1,
        validate_string_max_length: 255,
        validate_number_min: null,
        validate_number_max: null,
        validate_number_precision: null,
        validate_number_scale: null,
      },
      insert: {
        label: "Organisation type",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: true,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      update: {
        label: "Organisation type",
        short_description: null,
        format: "extensions.citext.as_is",
        allowed: true,
        required: false,
        default: null,
        default_expression: null,
        gcomponent: "GComponentInputText",
      },
      datatable: {
        label: "Organisation type",
        short_description: null,
        format: "extensions.citext.as_is",
        can_be_visible_in_table: true,
        default_visible_in_table: true,
        sortable: true,
        filterable: true,
        default_sort: null,
      },
      references: null,
      isIdColumn: false,
    },
  },
};
